/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __map_data_t_hpp__
#define __map_data_t_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>
#include <vector>


class map_data_t
{
    public:
        std::string map_name;

        float      map_grid_w;

        int32_t    map_w;

        int32_t    map_h;

        int32_t    map_origin[2];

        int32_t    len;

        std::vector< uint8_t > data;

        int32_t    via_num;

        std::vector< std::vector< float > > via_pos;

        int32_t    loc_num;

        std::vector< std::string > loc_name;

        std::vector< std::vector< float > > loc_pos;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "map_data_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int map_data_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int map_data_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int map_data_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t map_data_t::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* map_data_t::getTypeName()
{
    return "map_data_t";
}

int map_data_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* map_name_cstr = const_cast<char*>(this->map_name.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &map_name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->map_grid_w, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->map_w, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->map_h, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->map_origin[0], 2);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->len, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->len > 0) {
        tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->data[0], this->len);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->via_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->via_num; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->via_pos[a0][0], 3);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->loc_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->loc_num; a0++) {
        char* __cstr = const_cast<char*>(this->loc_name[a0].c_str());
        tlen = __string_encode_array(
            buf, offset + pos, maxlen - pos, &__cstr, 1);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->loc_num; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->loc_pos[a0][0], 3);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int map_data_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __map_name_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__map_name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__map_name_len__ > maxlen - pos) return -1;
    this->map_name.assign(
        static_cast<const char*>(buf) + offset + pos, __map_name_len__ - 1);
    pos += __map_name_len__;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->map_grid_w, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->map_w, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->map_h, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->map_origin[0], 2);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->len, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->len) {
        this->data.resize(this->len);
        tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->data[0], this->len);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->via_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->via_pos.resize(this->via_num);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->via_num; a0++) {
        if(3) {
            this->via_pos[a0].resize(3);
            tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->via_pos[a0][0], 3);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->loc_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->loc_name.resize(this->loc_num);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->loc_num; a0++) {
        int32_t __elem_len;
        tlen = __int32_t_decode_array(
            buf, offset + pos, maxlen - pos, &__elem_len, 1);
        if(tlen < 0) return tlen; else pos += tlen;
        if(__elem_len > maxlen - pos) return -1;
        this->loc_name[a0].assign(static_cast<const char*>(buf) + offset + pos, __elem_len -  1);
        pos += __elem_len;
    }

    try {
        this->loc_pos.resize(this->loc_num);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->loc_num; a0++) {
        if(3) {
            this->loc_pos[a0].resize(3);
            tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->loc_pos[a0][0], 3);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    return pos;
}

int map_data_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->map_name.size() + 4 + 1;
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 2);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __byte_encoded_array_size(NULL, this->len);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->via_num * __float_encoded_array_size(NULL, 3);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->loc_num; a0++) {
        enc_size += this->loc_name[a0].size() + 4 + 1;
    }
    enc_size += this->loc_num * __float_encoded_array_size(NULL, 3);
    return enc_size;
}

uint64_t map_data_t::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x61d84573d74996eaLL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
